services:
   - type: web
     name: solocker
     runtime: node
     plan: free
     autoDeploy: true
     buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
     startCommand: pnpm run serve
     env:
       fromGroup: solocker
